#terraform.tfvars
region = "us-east-2"
vpc_id        = "aws_vpc.rds_vpc.id"
priv_one_cidr = "10.0.1.0/24"
priv_two_cidr = "10.0.2.0/24"
az_one        = "us-east-2a"
az_two        = "us-east-2b"
vpc_cidr      = "10.0.0.0/16"
dns_support   = "true"
dns_hostnames = "true"